### ISSUE TITLE
List uploading stop working

### ISSUE THREAD

**Issue by asterriya** [luxysiv/Cloudflare-Gateway-Pihole#37]
Here is a log:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 148, in <module>
    asyncio.run(main())
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 145, in main
    await cloudflaremanager.run()
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 98, in run
    cf_lists = await asyncio.gather(*create_list_tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/cloudflare.py", line 14, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/cloudflare.py", line 43, in create_list
    raise Exception("Failed to create Cloudflare list")
Exception: Failed to create Cloudflare list
Error: Process completed with exit code 1.

And this error happens almost for all lists in domains / host format. But yesterday all works fine.

**Comment by misanthroope** [comment]
same here , i delete the repository and fork a new one but it's the same!

**Comment by nhathoang24** [comment]
same here !

**Comment by misanthroope** [comment]
do you guys if there's a good easy one on GitHub with auto refresh list? i found one but it's manual list

**Comment by luxysiv** [comment]
Some time python works fail. So I make retry for that issue

**Comment by luxysiv** [comment]
Oh, I was check. Problem belonging to Cloudflare server.

**Comment by luxysiv** [comment]
> Do we simply wait and try running the python script at a later time? Is that the solution you are implying?

Sometimes Cloudflare Gateway Zero Trust does not respond causing script errors.  So I let it run 3 times.  I just tested the script that runs on the requests library.  It also fails like aiohttp

**Comment by luxysiv** [comment]
In this case the error is the same as many months ago.  Yesterday I tried to access the Cloudflare Workers Pages but kept getting errors

**Comment by luxysiv** [comment]
![Screenshot_2024-06-06-11-27-15-795_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/1347ffee-892c-406a-9f18-9ebd7abe0cd7)

**Comment by asterriya** [comment]
Seems like Cloudflare changed something on worker page side.

**Comment by luxysiv** [comment]
![Screenshot_2024-06-06-18-23-19-194_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/8b631d75-a1eb-4f85-9361-cc0ecb78ca85)
I think it's a problem CF API. If the list < 70 , it works fine

**Comment by asterriya** [comment]
Thought the same before and even changed CF API, but still the same.

**Comment by luxysiv** [comment]
I think lists on CF Zero Trust less 65

**Comment by luxysiv** [comment]
It is very possible that Cloudflare rejects asyncio requests.  If next week the situation is still the same, I will publish the code using request and patch the lists.  It's better that when we update the lists the blocking ability is still valid

**Comment by luxysiv** [comment]
Now you can visit 
https://github.com/luxysiv/Cloudflare-Gateway-Package
Choose mode patch - run and total domains ~ 70k

**Comment by luxysiv** [comment]
> > Now you can visit https://github.com/luxysiv/Cloudflare-Gateway-Package Choose mode patch - run and total domains ~ 70k
> 
> The instructions say: "Set Variables, Please read Cloudflare-Gateway-Pihole", but the link provided does not mention how to do this.
> 
> Also, the instructions mention: "So you can create and paste this code to run on Cloudflare Workers.", but I do not know how to do this. What do you recommend I read or watch to understand how to do this?

The same like CGP

**Comment by luxysiv** [comment]
Package is Cloudflare Gateway Pihole add python environment and modules

**Comment by luxysiv** [comment]
> > Package is Cloudflare Gateway Pihole add python environment and modules
> 
> I apologize again for being dumb, but your replies continue to be cryptic. Do you mean we add the Python files to our existing local git package and run it in Termux?
Maybe. I not try do it on Termux. But I think It can

**Comment by luxysiv** [comment]
chmod +x Cloudflare-Gateway-Pihole && ./Cloudflare-Gateway-Pihole leave
chmod +x Cloudflare-Gateway-Pihole && ./Cloudflare-Gateway-Pihole run

**Comment by luxysiv** [comment]
Do not use Cloudflare-Gateway-Pihole, Pls use Cloudflare-Gateway-Pyhole

**Comment by luxysiv** [comment]
Ok, I try to sleep 2s before update or creat list. Maybe Cloudflare blocks sending requests to the system too quickly

**Comment by luxysiv** [comment]
This code no care about Github Action run. It patches lists. And when patched, block ads still vallid

**Comment by luxysiv** [comment]
I think true. Script works well when sleep 2s before send next request

**Comment by luxysiv** [comment]
> > This code no care about Github Action run. It patches lists. And while patching lists, block ads still vallid
> 
> I do not know how to use Clouflare Workers and for you to teach me how to do it is out of your scope.
> 
> So the Termux instructions, which for some reason you removed from the main Cloudflare-Gateway-Pihole repo, works for me running in Termux on my phone which has more than enough performance to run your script.
> 
> We will wait for you to update the repo and try again and report here to you any changes

Because last year, I tried to install aiohttp on Termux but not success. New update will use requests, it can install on termux fine. So you can run on Termux. But this script will take 4 minutes to run script or more. So Github Action is best.
Pls wait, I go to sleep. Good night

**Comment by luxysiv** [comment]
Script is back in operation. This time the mechanism works to patch lists if they already exist, delete or create the necessary lists. Script will operate at a slow speed. When Script is active the blocking effect is still available. Please delete old lists manually (clean any lists) so that the Script works correctly. Thank you.

**Comment by asterriya** [comment]
No. It still doesn't work. I made sync fork and error still happening even with new lists. All firewall rules were cleared.

**Comment by asterriya** [comment]
Run python -m src
2024-06-07 08:10:18.452 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/SystemJargon/filters/main/ads.txt File size: 5364997
2024-06-07 08:10:18.542 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/SystemJargon/filters/main/telemetry.txt File size: 77051
2024-06-07 08:10:[18](https://github.com/asterriya/Cloudflare-Gateway-Pihole/actions/runs/9413794336/job/25931310039#step:5:19).961 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/missdeer/blocklist/master/convert/alldomains.txt File size: 8089224
2024-06-07 08:10:18.968 | INFO     | src:info:50 - Number of whitelisted domains: 0
[20](https://github.com/asterriya/Cloudflare-Gateway-Pihole/actions/runs/9413794336/job/25931310039#step:5:21)24-06-07 08:10:20.773 | INFO     | src:info:50 - Number of blocked domains: 296[21](https://github.com/asterriya/Cloudflare-Gateway-Pihole/actions/runs/9413794336/job/25931310039#step:5:22)2
2024-06-07 08:10:20.883 | INFO     | src:info:50 - Number of final domains: 296212
2024-06-07 08:10:24.282 | ERROR    | src:error:43 - Failed to get current lists after retries
Error: Process completed with exit code 1.

**Comment by luxysiv** [comment]
![Screenshot_2024-06-07-15-37-03-949_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/7b4ea0fa-7cb8-4417-80f0-a94fd4e6c797)
It works fine. Maybe you not yet add variables

**Comment by asterriya** [comment]
If you mean CF and API tokens, it's added already.

**Comment by luxysiv** [comment]
Please see my Github Action, it works fine

**Comment by luxysiv** [comment]
@asterriya clean your lists on CF

**Comment by asterriya** [comment]
> @asterriya clean your lists on CF

Yes. I did that already. It's clear. Also, I forked repository from the scratch. And followed the same instructions. But still the same error.

**Comment by luxysiv** [comment]
@asterriya Update the script and try running again. If you haven’t succeeded then run again. The code will run successfully. See the log here 
https://github.com/luxysiv/Cloudflare-Gateway-Pihole/actions/runs/9418540542/job/25946246736

**Comment by luxysiv** [comment]
@misanthroope @n0w33d @nhathoang24 update code

**Comment by asterriya** [comment]
@luxysiv I synced fork, and it goes now for infinite loop. 6 minutes passed, but it's still showing update rules and passed over 200 rules. Which isn't real.

**Comment by asterriya** [comment]
> Please alspo update the cf gateway package with these latest update.

what do you mean?

**Comment by suricloud** [comment]
> > Please alspo update the cf gateway package with these latest update.
> 
> what do you mean?
sorry this is for @luxysiv

**Comment by luxysiv** [comment]
> @luxysiv I synced fork, and it goes now for infinite loop. 6 minutes passed, but it's still showing update rules and passed over 200 rules. Which isn't real. I even try to create from the start repo and still the same infinite loop.

First you can run delete CF lists. This update I was check all today. It's work very well

**Comment by luxysiv** [comment]
> Please alspo update the cf gateway package with these latest update.

Done

**Comment by suricloud** [comment]
> > Please alspo update the cf gateway package with these latest update.
> 
> Done

Thanks :)

**Comment by luxysiv** [comment]
Retry, see my Github Action to know it works fine @suricloud

**Comment by luxysiv** [comment]
@asterriya your list is big and it need 12 minutes to run.
Because CF reject connection too fast, so this script now run very slow.

**Comment by suricloud** [comment]
> Retry, see my Github Action to know it works fine @suricloud

I retried 3 times, same error ?

**Comment by asterriya** [comment]
> First you can run delete CF lists. This update I was check all today. It works very well

As I told, firewall rules were deleted. I thought before that my list can be big, and I checked with a small one. But still the same loop. Even with those lists that placed in original repo.

**Comment by suricloud** [comment]
> > Retry, see my Github Action to know it works fine @suricloud
> 
> I retried 3 times, same error ?

Tried again, and now updated :)
Thanks.

**Comment by luxysiv** [comment]
I'll add infinite repetition. Will add the maximum runtime setting github actions

**Comment by luxysiv** [comment]
It ensures no errors when running GitHub Actions but there will be problems if the Cloudflare server fails so it will limit GitHub Actions runtime

**Comment by luxysiv** [comment]
![IMG_20240608_090051_048](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/5b188be6-af45-4f5a-8784-8ae678bec144)
Due to Cloudflare protection, not script errors

**Comment by luxysiv** [comment]
@n0w33d Termux works again
![Screenshot_2024-06-08-11-52-29-269_com termux](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/5c5858ca-9961-4187-aee0-5e89a25dd74a)

**Comment by luxysiv** [comment]
> > Do not use Cloudflare-Gateway-Pihole, Pls use Cloudflare-Gateway-Pyhole
> 
> That is so confusing.
> 
> Well I've done a git pull on both repositories you have, copied both files over ([...]Pyhole and [...]Pihole) to one directory above "src" and tried to run both with chmod 777 properties, and the error is similar for both files: `bash: ./Cloudflare-Gateway-Pyhole: cannot execute binary file: Exec format error`
> 
> However running `python -m src` still works but always fails with the same error OP posted as the first message of this discussion.

This file can't run on Termux. Because it's 86_64 bin file

**Comment by luxysiv** [comment]
You're welcome. Actually, you can fork and delete time.sleep. I think requests from Github server to Cloudflare server too fast

**Comment by axelweichert** [comment]
I am getting this:
Run python -m src
2024-06-10 08:50:41.740 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt File size: 1244590
2024-06-10 08:50:42.010 | INFO     | src:info:50 - Downloaded file from https://gitlab.com/fusionjack/adhell3-hosts/-/raw/master/hosts File size: 218535
2024-06-10 08:50:43.655 | INFO     | src:info:50 - Downloaded file from https://abpvn.com/android/abpvn.txt File size: 600492
2024-06-10 08:50:43.668 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt File size: 9218
2024-06-10 08:50:43.751 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi File size: 217
2024-06-10 08:50:43.785 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt File size: 4437
2024-06-10 08:50:43.869 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung File size: 92
2024-06-10 08:50:44.237 | INFO     | src:info:50 - Downloaded file from https://malware-filter.gitlab.io/malware-filter/vn-badsite-filter-hosts.txt File size: 374452
2024-06-10 08:50:44.286 | INFO     | src:info:50 - Downloaded file from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt File size: [14](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9445349792/job/26012757457#step:5:15)17556
2024-06-10 08:50:45.092 | INFO     | src:info:50 - Downloaded file from https://small.oisd.nl/domainswild2 File size: 840485
2024-06-10 08:50:45.093 | INFO     | src:info:50 - Number of whitelisted domains: 1
2024-06-10 08:50:45.881 | INFO     | src:info:50 - Number of blocked domains: 122503
2024-06-10 08:50:45.9[16](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9445349792/job/26012757457#step:5:17) | INFO     | src:info:50 - Number of final domains: 122502
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 86, in <module>
    cloudflare_manager.run()
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in run
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in <lambda>
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.

**Comment by luxysiv** [comment]
Try re-input variables

**Comment by axelweichert** [comment]
> Try re-input variables and check your list on Zero Trust. If has, pls delete it . It works fine https://github.com/luxysiv/Cloudflare-Gateway-Pihole/actions/runs/9446977777/job/26017779738

Thanks, but which variable do you mean? Secret an CF Identifiyer? Have re-enterd them, but again the same message.

**Comment by luxysiv** [comment]
Delete your fork and re-fork. This issue had when CGZT non list on that. But I was fix

**Comment by luxysiv** [comment]
@axelweichert can you DM me your account and password. I will try to fix. Thanks

**Comment by axelweichert** [comment]
I have reforked it, deleted all AdLists, but still same message.  I will try, but i have 2FA enabled.

**Comment by asterriya** [comment]
@luxysiv It's worked before and uploaded. Check it on your side.
SystemJargon = https://raw.githubusercontent.com/SystemJargon/filters/main/ads.txt
SystemJargon = https://raw.githubusercontent.com/SystemJargon/filters/main/telemetry.txt
