### ISSUE TITLE
I am getting this since 5 days. Before everything was running fine.

### ISSUE THREAD

**Issue by luxysiv** [luxysiv/Cloudflare-Gateway-Pihole#40]
I am getting this since 5 days. Before everything was running fine.

Run python -m src
2024-06-10 08:50:41.740 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt File size: 1244590
2024-06-10 08:50:42.010 | INFO     | src:info:50 - Downloaded file from https://gitlab.com/fusionjack/adhell3-hosts/-/raw/master/hosts File size: 218535
2024-06-10 08:50:43.655 | INFO     | src:info:50 - Downloaded file from https://abpvn.com/android/abpvn.txt File size: 600492
2024-06-10 08:50:43.668 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt File size: 9218
2024-06-10 08:50:43.751 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi File size: 217
2024-06-10 08:50:43.785 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt File size: 4437
2024-06-10 08:50:43.869 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung File size: 92
2024-06-10 08:50:44.237 | INFO     | src:info:50 - Downloaded file from https://malware-filter.gitlab.io/malware-filter/vn-badsite-filter-hosts.txt File size: 374452
2024-06-10 08:50:44.286 | INFO     | src:info:50 - Downloaded file from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt File size: [14](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9445349792/job/26012757457#step:5:15)17556
2024-06-10 08:50:45.092 | INFO     | src:info:50 - Downloaded file from https://small.oisd.nl/domainswild2 File size: 840485
2024-06-10 08:50:45.093 | INFO     | src:info:50 - Number of whitelisted domains: 1
2024-06-10 08:50:45.881 | INFO     | src:info:50 - Number of blocked domains: 122503
2024-06-10 08:50:45.9[16](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9445349792/job/26012757457#step:5:17) | INFO     | src:info:50 - Number of final domains: 122502
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 86, in <module>
    cloudflare_manager.run()
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in run
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in <lambda>
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.

_Originally posted by @axelweichert in https://github.com/luxysiv/Cloudflare-Gateway-Pihole/issues/37#issuecomment-2157862075_

**Comment by luxysiv** [comment]
@axelweichert Can you sync? If it works, please let me know.

**Comment by axelweichert** [comment]
> @axelweichert Can you sync? If it works, please let me know.

Still the same error message. 

6s
Run python -m src
2024-06-[1](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9449790581/job/26026905132#step:5:1)0 14:03:09.068 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/light-onlydomains.txt File size: 1244590
2024-06-10 [14](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9449790581/job/26026905132#step:5:15):03:09.281 | INFO     | src:info:50 - Downloaded file from https://gitlab.com/fusionjack/adhell3-hosts/-/raw/master/hosts File size: 218535
2024-06-10 14:03:11.372 | INFO     | src:info:50 - Downloaded file from https://abpvn.com/android/abpvn.txt File size: 600492
2024-06-10 14:03:11.382 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt File size: 9218
2024-06-10 14:03:11.392 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/xiaomi File size: 2[17](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9449790581/job/26026905132#step:5:18)
2024-06-10 14:03:11.401 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt File size: 4437
2024-06-10 14:03:11.413 | INFO     | src:info:50 - Downloaded file from https://raw.githubusercontent.com/nextdns/native-tracking-domains/main/domains/samsung File size: 92
2024-06-10 14:03:11.703 | INFO     | src:info:50 - Downloaded file from https://malware-filter.gitlab.io/malware-filter/vn-badsite-filter-hosts.txt File size: 374452
2024-06-10 14:03:11.733 | INFO     | src:info:50 - Downloaded file from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt File size: 14176[18](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9449790581/job/26026905132#step:5:19)
2024-06-10 14:03:12.389 | INFO     | src:info:50 - Downloaded file from https://small.oisd.nl/domainswild2 File size: 843148
2024-06-10 14:03:12.390 | INFO     | src:info:50 - Number of whitelisted domains: 1
2024-06-10 14:03:13.174 | INFO     | src:info:50 - Number of blocked domains: 122607
2024-06-10 14:03:13.209 | INFO     | src:info:50 - Number of final domains: 122606
Traceback (most recent call last):
  File "<frozen runpy>", line [19](https://github.com/axelweichert/Cloudflare-Gateway-Pihole/actions/runs/9449790581/job/26026905132#step:5:20)8, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 86, in <module>
    cloudflare_manager.run()
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in run
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 41, in <lambda>
    current_lists["result"].sort(key=lambda x: int(re.search(r'\d+', x["name"]).group()))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
Error: Process completed with exit code 1.

**Comment by luxysiv** [comment]
You're not update script

**Comment by luxysiv** [comment]
Please update your forked @axelweichert

**Comment by axelweichert** [comment]
It runs perfect. Many thanks for your help.

**Comment by luxysiv** [comment]
> It runs perfect. Many thanks for your help.

Thanks for your issue notice
