### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by asterriya** [luxysiv/Cloudflare-Gateway-Pihole#42]
Run python -m src run
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/__main__.py", line 2, in <module>
    from src import (
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/utils.py", line 3, in <module>
    from src import (
  File "/home/runner/work/Cloudflare-Gateway-Pihole/Cloudflare-Gateway-Pihole/src/cloudflare.py", line 2, in <module>
    from tenacity import (
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tenacity.asyncio'
Error: Process completed with exit code 1.

**Comment by luxysiv** [comment]
Thanks, I'm fixing now

**Comment by luxysiv** [comment]
Done
